const assert = require('assert')
const { read } = require('./rc9_test_helpers')

const score = read('pages/score-trend/score-trend.wxml')
const targets = read('pages/targets/targets.wxml')
assert.ok(score.includes('最高'))
assert.ok(score.includes('最低'))
assert.ok(score.includes('平均'))
assert.ok(score.includes('最近变化'))
for (const label of ['冲刺', '目标', '保底']) assert.ok(targets.includes(label))
assert.ok(targets.includes('status-badge'))
assert.strictEqual(score.includes('<image'), false)
assert.strictEqual(targets.includes('<image'), false)
console.log('RC10 ACCESSIBILITY VERIFY PASSED')
