const assert = require('assert')
const { APP_CONFIG, EXAM_TOTAL_SCORE } = require('../config/app-config')
const { schools } = require('../data/schools')
const { admissionScores } = require('../data/admission-scores')
const { MP13_2026_VERIFIED_COUNT } = require('../data/admission-scores-2026')

assert.strictEqual(APP_CONFIG.name, '苏程记录')
assert.strictEqual(APP_CONFIG.schoolData.publicApiBase, 'https://api.royalcup.top')
assert.strictEqual(APP_CONFIG.schoolData.supportedSchemaVersion, 2)
assert.strictEqual(EXAM_TOTAL_SCORE, 740)
assert.strictEqual(schools.length, 55)
assert.strictEqual(admissionScores.length, 146)
assert.strictEqual(admissionScores.filter((item) => item.year === 2025).length, 103)
assert.strictEqual(admissionScores.filter((item) => item.year === 2026).length, MP13_2026_VERIFIED_COUNT)
assert.ok(admissionScores.every((item) => Number.isInteger(item.minScore) && item.minScore >= 0 && item.minScore <= EXAM_TOTAL_SCORE))
assert.strictEqual(new Set(admissionScores.map((item) => item.id)).size, admissionScores.length)
assert.ok(admissionScores.every((item) => schools.some((school) => school.id === item.schoolId)))

console.log('MP5 STATIC VERIFY PASSED（55校 / 103+43分数 / 740 / 正式API配置）')
